import { CountriesOption } from '../types/types';

const countries: CountriesOption[] = [
  { label: 'Andorra', value: 'andorra', iso: 'AD' },
  { label: 'Argentina', value: 'argentina', iso: 'AR' },
  { label: 'Austria', value: 'austria', iso: 'AT' },
  { label: 'Australia', value: 'australia', iso: 'AU' },
  { label: 'Bangladesh', value: 'bangladesh', iso: 'BD' },
  { label: 'Belgium', value: 'belgium', iso: 'BE' },
  { label: 'Brazil', value: 'brazil', iso: 'BR' },
  { label: 'Bulgaria', value: 'bulgaria', iso: 'BG' },
  { label: 'Canada', value: 'canada', iso: 'CA' },
  { label: 'Croatia', value: 'croatia', iso: 'HR' },
  { label: 'Czech Republic', value: 'czech republic', iso: 'CZ' },
  { label: 'Denmark', value: 'denmark', iso: 'DK' },
  { label: 'Dominican Republic', value: 'dominican republic', iso: 'DO' },
  { label: 'Faroe Islands', value: 'faroe islands', iso: 'FO' },
  { label: 'Finland', value: 'finland', iso: 'FI' },
  { label: 'France', value: 'france', iso: 'FR' },
  { label: 'Germany', value: 'germany', iso: 'DE' },
  { label: 'Greenland', value: 'greenland', iso: 'GL' },
  { label: 'Guadeloupe', value: 'guadeloupe', iso: 'GP' },
  { label: 'Guernsey', value: 'guernsey', iso: 'GG' },
  { label: 'Guatemala', value: 'guatemala', iso: 'GT' },
  { label: 'Guam', value: 'guam', iso: 'GU' },
  { label: 'Hungary', value: 'hungary', iso: 'HU' },
  { label: 'Iceland', value: 'iceland', iso: 'IS' },
  { label: 'India', value: 'india', iso: 'IN' },
  { label: 'Isle of Man', value: 'isle of man', iso: 'IM' },
  { label: 'Italy', value: 'italy', iso: 'IT' },
  { label: 'Jersey', value: 'jersey', iso: 'JE' },
  { label: 'Japan', value: 'japan', iso: 'JP' },
  { label: 'Liechtenstein', value: 'liechtenstein', iso: 'LI' },
  { label: 'Luxembourg', value: 'luxembourg', iso: 'LU' },
  { label: 'Macedonia', value: 'macedonia', iso: 'MK' },
  { label: 'Marshall Islands', value: 'marshall islands', iso: 'MH' },
  { label: 'Malaysia', value: 'malaysia', iso: 'MY' },
  { label: 'Martinique', value: 'martinique', iso: 'MQ' },
  { label: 'Mayotte', value: 'mayotte', iso: 'YT' },
  { label: 'Mexico', value: 'mexico', iso: 'MX' },
  { label: 'Moldova', value: 'moldova', iso: 'MD' },
  { label: 'Monaco', value: 'monaco', iso: 'MC' },
  { label: 'Netherlands', value: 'netherlands', iso: 'NL' },
  { label: 'New Zealand', value: 'new zealand', iso: 'NZ' },
  { label: 'Norway', value: 'norway', iso: 'NO' },
  { label: 'Northern Mariana Islands', value: 'northern mariana islands', iso: 'MP' },
  { label: 'Pakistan', value: 'pakistan', iso: 'PK' },
  { label: 'Philippines', value: 'philippines', iso: 'PH' },
  { label: 'Poland', value: 'poland', iso: 'PL' },
  { label: 'Portugal', value: 'portugal', iso: 'PT' },
  { label: 'Puerto Rico', value: 'puerto rico', iso: 'PR' },
  { label: 'Lithuania', value: 'lithuania', iso: 'LT' },
  { label: 'Russia', value: 'russia', iso: 'RU' },
  { label: 'Réunion', value: 'réunion', iso: 'RE' },
  { label: 'San Marino', value: 'san marino', iso: 'SM' },
  { label: 'Saint Pierre and Miquelon', value: 'saint pierre and miquelon', iso: 'PM' },
  { label: 'Slovakia', value: 'slovakia', iso: 'SK' },
  { label: 'Slovenia', value: 'slovenia', iso: 'SI' },
  { label: 'South Africa', value: 'south africa', iso: 'ZA' },
  { label: 'Spain', value: 'spain', iso: 'ES' },
  { label: 'Sri Lanka', value: 'sri lanka', iso: 'LK' },
  { label: 'Sweden', value: 'sweden', iso: 'SE' },
  { label: 'Switzerland', value: 'switzerland', iso: 'CH' },
  { label: 'Thailand', value: 'thailand', iso: 'TH' },
  { label: 'Turkey', value: 'turkey', iso: 'TR' },
  { label: 'United Kingdom', value: 'united kingdom', iso: 'GB' },
  { label: 'United States', value: 'united states', iso: 'US' },
  { label: 'Vatican City State (Holy See)', value: 'vatican city state (holy see)', iso: 'VA' },
];

export default countries;
